//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Desk.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=C-4-PC;Initial Catalog=AllInOneInventoryWithGST;Persist Security Info" +
            "=True;User ID=sa;Password=admin@123")]
        public string AllInOneInventoryWithGSTConnectionString1 {
            get {
                return ((string)(this["AllInOneInventoryWithGSTConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TFSSERVER\\SQL2005;Initial Catalog=AllInOneIntegrated;Persist Security" +
            " Info=True;User ID=sa;Password=admin@123")]
        public string AllInOneIntegratedConnectionString {
            get {
                return ((string)(this["AllInOneIntegratedConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-7U8MGDM\\SQLEXPRESS;Initial Catalog=DbBharatScale;User ID=sa;P" +
            "assword=admin@123;MultipleActiveResultSets=True")]
        public string SwamiSamarthConnectionString {
            get {
                return ((string)(this["SwamiSamarthConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-7U8MGDM\\SQLEXPRESS;Initial Catalog=DbBharatScale;User ID=sa;P" +
            "assword=admin@123")]
        public string GokulConnectionString {
            get {
                return ((string)(this["GokulConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-7U8MGDM\\SQLEXPRESS;Initial Catalog=DbBharatScale;Persist Secu" +
            "rity Info=True;User ID=sa;Password=admin@123")]
        public string DBShreeKrushanTradersConnectionString {
            get {
                return ((string)(this["DBShreeKrushanTradersConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-7U8MGDM\\SQLEXPRESS;Initial Catalog=DbBharatScale;Persist Secu" +
            "rity Info=True;User ID=sa;Password=admin@123")]
        public string AllInOneInventoryDBConnectionString {
            get {
                return ((string)(this["AllInOneInventoryDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-7U8MGDM\\SQLEXPRESS;Initial Catalog=DbBharatScale;User ID=sa;P" +
            "assword=admin@123")]
        public string AllInOneInventoryWithGSTConnectionString {
            get {
                return ((string)(this["AllInOneInventoryWithGSTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=C-4-PC;Initial Catalog=DbBharatScale;User ID=sa;Password=admin@123")]
        public string DattTradersTakariGSTConnectionString {
            get {
                return ((string)(this["DattTradersTakariGSTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-7U8MGDM\\SQLEXPRESS;Initial Catalog=DBintegration27Mar20;Persi" +
            "st Security Info=True;User ID=sa;Password=admin@123")]
        public string DBintegration27Mar20ConnectionString {
            get {
                return ((string)(this["DBintegration27Mar20ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-7U8MGDM\\SQLEXPRESS;Initial Catalog=DBNewIntegration;Persist S" +
            "ecurity Info=True;User ID=sa;Password=admin@123")]
        public string DBNewIntegrationConnectionString {
            get {
                return ((string)(this["DBNewIntegrationConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-7U8MGDM\\SQLEXPRESS;Initial Catalog=DbBharatScale;Persist Secu" +
            "rity Info=True;User ID=sa;Password=admin@123")]
        public string DbAjinkyaAutoUmbrajConnectionString {
            get {
                return ((string)(this["DbAjinkyaAutoUmbrajConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-7U8MGDM\\SQLEXPRESS;Initial Catalog=DbBharatScale;Persist Secu" +
            "rity Info=True;User ID=sa;Password=admin@123")]
        public string DbAjinkyaAutoUmbrajConnectionString1 {
            get {
                return ((string)(this["DbAjinkyaAutoUmbrajConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-7U8MGDM\\SQLEXPRESS;Initial Catalog=DBAutoBiz;User ID=sa;Passw" +
            "ord=admin@123")]
        public string DBAutoBizConnectionString {
            get {
                return ((string)(this["DBAutoBizConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-66VBN2I\\SQLEXPRESS;Initial Catalog=DbBharatScal;User ID=sa;Pa" +
            "ssword=admin@123")]
        public string DbBharatScalConnectionString {
            get {
                return ((string)(this["DbBharatScalConnectionString"]));
            }
        }
    }
}
