//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillWiseSupplierReceipt
    {
        public int Id { get; set; }
        public Nullable<int> SupplierReceiptNo { get; set; }
        public Nullable<int> BillId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> RemainigAmount { get; set; }
        public string TransactionYear { get; set; }
        public Nullable<int> CompId { get; set; }
    }
}
