//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInformation
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public string Website { get; set; }
        public string VatNo { get; set; }
        public string TinNo { get; set; }
        public byte[] Logo { get; set; }
        public string BankName { get; set; }
        public string BankAcNo { get; set; }
        public string IFSCCode { get; set; }
        public string State { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string CompNameMarathi { get; set; }
        public string CompAddMarathi { get; set; }
        public string SeedLicNo { get; set; }
        public string InscLicNo { get; set; }
        public string FertLicNo { get; set; }
        public string RetailerFertLicNo { get; set; }
        public string FSSAINo { get; set; }
        public string PadtalaniNo { get; set; }
    }
}
