//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeadProductDetail
    {
        public int Id { get; set; }
        public Nullable<int> DeadNo { get; set; }
        public string ProductName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public string SaleUnit { get; set; }
        public string Code { get; set; }
        public string Barcode { get; set; }
        public string BatchNo { get; set; }
        public string ColorName { get; set; }
        public string Size { get; set; }
        public string DeptName { get; set; }
        public string Category { get; set; }
    
        public virtual DeadProductMaster DeadProductMaster { get; set; }
    }
}
