//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryChallanDetail
    {
        public int Id { get; set; }
        public Nullable<int> DeliveryChallanNo { get; set; }
        public string ProductName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public string Code { get; set; }
        public string SaleUnit { get; set; }
    
        public virtual DeliveryChallanMaster DeliveryChallanMaster { get; set; }
    }
}
