//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expence
    {
        public int Id { get; set; }
        public int ExpenceID { get; set; }
        public Nullable<System.DateTime> ExpenceDate { get; set; }
        public string ExpenceName { get; set; }
        public string FromPerson { get; set; }
        public string ToPerson { get; set; }
        public string Reason { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public string Bankname { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string TransactionYear { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> ACGId { get; set; }
    
        public virtual AccountingGroupMaster AccountingGroupMaster { get; set; }
    }
}
