//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FestivalTemplate
    {
        public int Id { get; set; }
        public Nullable<int> FestivalTemplateNo { get; set; }
        public Nullable<int> FestivalId { get; set; }
        public string FestivalName { get; set; }
        public string FestivalsMessage { get; set; }
    }
}
