//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeMaster
    {
        public IncomeMaster()
        {
            this.Incomes = new HashSet<Income>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IncomeId { get; set; }
        public string IncomeName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ACGId { get; set; }
        public Nullable<int> CompId { get; set; }
    
        public virtual AccountingGroupMaster AccountingGroupMaster { get; set; }
        public virtual ICollection<Income> Incomes { get; set; }
    }
}
