//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        public int Id { get; set; }
        public Nullable<int> JENo { get; set; }
        public Nullable<System.DateTime> JEDate { get; set; }
        public Nullable<int> FromAccountId { get; set; }
        public string FromAccountName { get; set; }
        public Nullable<int> ToAccountId { get; set; }
        public string ToAccountName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionYear { get; set; }
        public Nullable<int> CompId { get; set; }
        public string FromGroup { get; set; }
        public string ToGroup { get; set; }
    }
}
