//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MistriInformation
    {
        public int Id { get; set; }
        public Nullable<int> MistriCode { get; set; }
        public string MistriName { get; set; }
        public string MistriAddress { get; set; }
        public string ContactNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> CompId { get; set; }
    }
}
