//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProprietorMaster
    {
        public int Id { get; set; }
        public Nullable<int> ProprietorId { get; set; }
        public string ProprietorName { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string Panno { get; set; }
        public string AdharCardNo { get; set; }
        public Nullable<int> ACGId { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<System.DateTime> OpeningBalanceDate { get; set; }
    
        public virtual AccountingGroupMaster AccountingGroupMaster { get; set; }
    }
}
