//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetailTrack
    {
        public int Id { get; set; }
        public Nullable<int> PorderNo { get; set; }
        public string ProductName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> FreeQty { get; set; }
        public string Code { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> CompId { get; set; }
    }
}
