//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecieptChallanMaster
    {
        public RecieptChallanMaster()
        {
            this.RecieptChalanDetails = new HashSet<RecieptChalanDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RecieptChallanNo { get; set; }
        public Nullable<System.DateTime> RecieptChallanDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> Status { get; set; }
        public string TransactionYear { get; set; }
        public Nullable<int> POrderNo { get; set; }
        public Nullable<int> CompId { get; set; }
        public string Challanno { get; set; }
    
        public virtual ICollection<RecieptChalanDetail> RecieptChalanDetails { get; set; }
    }
}
