//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        public int Id { get; set; }
        public Nullable<int> stockNo { get; set; }
        public string ProductName { get; set; }
        public string CompanyName { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> PurchaseQuantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
