//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public int SubCatId { get; set; }
        public string SubCatName { get; set; }
        public string SubCatCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<int> CompId { get; set; }
    }
}
