//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubGroupMaster
    {
        public int Id { get; set; }
        public string SubGroupName { get; set; }
        public Nullable<int> GroupMasterId { get; set; }
        public string Description { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> CompId { get; set; }
    }
}
