//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInformation
    {
        public int Id { get; set; }
        public Nullable<int> SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
        public string ContactNo { get; set; }
        public string EmailId { get; set; }
        public string VatNo { get; set; }
        public string TinNo { get; set; }
        public Nullable<int> CompId { get; set; }
        public string Panno { get; set; }
        public string LandlineNo { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public Nullable<System.DateTime> OpeningBalanceDate { get; set; }
        public string SeedLicNo { get; set; }
        public string InscLicNo { get; set; }
        public string FertiLicNo { get; set; }
        public string CSTNo { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string BankACNo { get; set; }
    
        public virtual StateMaster StateMaster { get; set; }
    }
}
