//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAllPurchaseListReport
    {
        public int Id { get; set; }
        public Nullable<int> PONo { get; set; }
        public string SuppInvNo { get; set; }
        public string PODate { get; set; }
        public string SupplierName { get; set; }
        public string GSTN { get; set; }
        public Nullable<decimal> GSTPer { get; set; }
        public Nullable<decimal> TaxableAmt { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> CessAmt { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public Nullable<decimal> DiscAmt { get; set; }
        public Nullable<decimal> SpDisc { get; set; }
        public Nullable<decimal> SpDiscAmt { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public string BillNo { get; set; }
        public Nullable<decimal> TotalPDiscAmt { get; set; }
        public Nullable<decimal> TotalPSpDiscAmt { get; set; }
    }
}
