//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillWiseCustomerLedger
    {
        public int Id { get; set; }
        public Nullable<int> RemPaymentId { get; set; }
        public string BillNo { get; set; }
        public Nullable<decimal> TotalBillAmount { get; set; }
        public Nullable<decimal> BillWisePaidAmount { get; set; }
        public Nullable<decimal> BillWiseRemAmount { get; set; }
        public Nullable<decimal> TotPaidAmtInReceipt { get; set; }
        public string Status { get; set; }
    
        public virtual RemainingPayment RemainingPayment { get; set; }
    }
}
