//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnvirnmentAndCurtainCoolpadSystemMaster
    {
        public tblEnvirnmentAndCurtainCoolpadSystemMaster()
        {
            this.tbEnvirnmentAndCurtainCoolpadSystemDetails = new HashSet<tbEnvirnmentAndCurtainCoolpadSystemDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public Nullable<int> VentilationQutNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Type { get; set; }
        public string ABCDSmart3g { get; set; }
        public string PanelModelA6 { get; set; }
        public string NoOfHuminiditySensorRHS { get; set; }
        public string CCommunicationMuxDCommunicationNNo { get; set; }
        public string CablesAndWiringLightsYESNO { get; set; }
        public Nullable<decimal> LengthOfCurtainSideA1 { get; set; }
        public Nullable<decimal> SideA2 { get; set; }
        public Nullable<decimal> LengthOfCurtainOnOtherSideB1 { get; set; }
        public Nullable<decimal> OnOtherSideB2 { get; set; }
        public Nullable<decimal> LengthOfCurtainOnBackCoolPad { get; set; }
        public Nullable<decimal> OnSidesCoolingPads { get; set; }
        public Nullable<decimal> SuspensionAtEveryFeet { get; set; }
        public Nullable<decimal> SideWallBottom { get; set; }
        public Nullable<decimal> SideWallTop { get; set; }
        public Nullable<decimal> WidthOfCurtainNeeded { get; set; }
        public string LouverSystem { get; set; }
        public string LectricWinch { get; set; }
        public string CurtainOnCoolPads { get; set; }
        public Nullable<decimal> CostOfTotalSystem { get; set; }
        public Nullable<decimal> CostPerHouse { get; set; }
        public Nullable<decimal> CostPerBird { get; set; }
        public Nullable<int> CompId { get; set; }
        public string TransactionYear { get; set; }
        public Nullable<decimal> CostOfTotalSystem1 { get; set; }
        public Nullable<decimal> EnvCurPercent { get; set; }
    
        public virtual ICollection<tbEnvirnmentAndCurtainCoolpadSystemDetail> tbEnvirnmentAndCurtainCoolpadSystemDetails { get; set; }
        public virtual tblProjectAtGlanceMaster tblProjectAtGlanceMaster { get; set; }
    }
}
