//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectAtGlanceMaster
    {
        public tblProjectAtGlanceMaster()
        {
            this.tblEnvirnmentAndCurtainCoolpadSystemMasters = new HashSet<tblEnvirnmentAndCurtainCoolpadSystemMaster>();
            this.tblNippleFeederSystemMasters = new HashSet<tblNippleFeederSystemMaster>();
            this.tblProjectGlanceDetails = new HashSet<tblProjectGlanceDetail>();
            this.tblVentilationAndCoolingSystems = new HashSet<tblVentilationAndCoolingSystem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> QutNo { get; set; }
        public string RefernceNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> LengthInFeet { get; set; }
        public Nullable<decimal> WidthInFeet { get; set; }
        public Nullable<decimal> HeightInFeet { get; set; }
        public Nullable<decimal> NoOfHouses { get; set; }
        public Nullable<decimal> SlopeInInch { get; set; }
        public Nullable<decimal> ServiceRoom { get; set; }
        public Nullable<decimal> SideHeightTop { get; set; }
        public Nullable<decimal> SideHeightTop1 { get; set; }
        public Nullable<decimal> SideHeightBottom { get; set; }
        public Nullable<decimal> SideHeightBottom1 { get; set; }
        public Nullable<decimal> BirdsAreaSqFt { get; set; }
        public Nullable<decimal> BirdsAreaSqFt1 { get; set; }
        public Nullable<decimal> SHEDAreaSqFt { get; set; }
        public Nullable<decimal> SHEDAreaSqFt1 { get; set; }
        public string TypeOfBird { get; set; }
        public Nullable<decimal> NoOfBirds { get; set; }
        public Nullable<decimal> NoOfBirds1 { get; set; }
        public Nullable<decimal> SQFTBIRD { get; set; }
        public Nullable<decimal> SQFTBIRD1 { get; set; }
        public Nullable<decimal> BIRDSPERSQMTR { get; set; }
        public Nullable<decimal> BIRDSPERSQMTR1 { get; set; }
        public Nullable<decimal> BIRDLIVEWT { get; set; }
        public Nullable<decimal> BIRDLIVEWT1 { get; set; }
        public string Type { get; set; }
        public string EC { get; set; }
        public string Cages { get; set; }
        public Nullable<decimal> LiveWTKgSqMt { get; set; }
        public Nullable<decimal> TotalNipples { get; set; }
        public Nullable<decimal> TotalEzypans { get; set; }
        public Nullable<decimal> BirdsPerNipples { get; set; }
        public Nullable<decimal> BirdsPerNipples1 { get; set; }
        public Nullable<decimal> BirdsPerPan1 { get; set; }
        public Nullable<decimal> BirdsPerPan { get; set; }
        public Nullable<decimal> AirSpeedFtMin { get; set; }
        public Nullable<decimal> NoOfFANS { get; set; }
        public Nullable<decimal> RecLengthOfLinesft { get; set; }
        public Nullable<decimal> NoOfNipplesLines { get; set; }
        public Nullable<decimal> NoOfFeedLinesLoops { get; set; }
        public Nullable<decimal> NipplesIn10FTSegment { get; set; }
        public Nullable<decimal> NipplesIn10FTSegment1 { get; set; }
        public Nullable<decimal> PansIn15FTSegment1 { get; set; }
        public Nullable<decimal> PansIn15FTSegment { get; set; }
        public Nullable<decimal> SuspentionPointsAtEveryFt { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<decimal> GSTAmt { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public Nullable<decimal> TotalHP { get; set; }
        public Nullable<int> CompId { get; set; }
        public string TransactionYear { get; set; }
        public string ShedSize { get; set; }
    
        public virtual CustomerInformation CustomerInformation { get; set; }
        public virtual StaffInfo StaffInfo { get; set; }
        public virtual ICollection<tblEnvirnmentAndCurtainCoolpadSystemMaster> tblEnvirnmentAndCurtainCoolpadSystemMasters { get; set; }
        public virtual ICollection<tblNippleFeederSystemMaster> tblNippleFeederSystemMasters { get; set; }
        public virtual ICollection<tblProjectGlanceDetail> tblProjectGlanceDetails { get; set; }
        public virtual ICollection<tblVentilationAndCoolingSystem> tblVentilationAndCoolingSystems { get; set; }
    }
}
