//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRemainingPaymentReport
    {
        public int Id { get; set; }
        public Nullable<int> BId { get; set; }
        public string BillNo { get; set; }
        public string UserSeries { get; set; }
        public string BillDate { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public string ReceiptDate { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public Nullable<decimal> PaidAmt { get; set; }
        public Nullable<decimal> BalAmt { get; set; }
        public string Mode { get; set; }
        public string BankName { get; set; }
        public string ChequeNo { get; set; }
        public string ChequeDate { get; set; }
        public string Narration { get; set; }
    }
}
