//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransactionYearDate
    {
        public int Id { get; set; }
        public string TransactionYear { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    }
}
