//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblunpaidBonusList
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> BId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> TotalBonusAmount { get; set; }
        public Nullable<decimal> PaidAmt { get; set; }
        public Nullable<decimal> RemainingAmt { get; set; }
        public string PaymentMode { get; set; }
        public string Bankname { get; set; }
        public string Chequeno { get; set; }
        public Nullable<System.DateTime> Chequedate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Status { get; set; }
        public string Narration { get; set; }
    }
}
