//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVentilationAndCoolingSystem
    {
        public tblVentilationAndCoolingSystem()
        {
            this.tblVentilationAndCoolingSystemDetails = new HashSet<tblVentilationAndCoolingSystemDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public Nullable<int> VentilationQutNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> TARGETTEMPF { get; set; }
        public Nullable<decimal> TARGETTEMPF1 { get; set; }
        public Nullable<decimal> DIFFFANTPAD { get; set; }
        public Nullable<decimal> TOTALHEATLOAD { get; set; }
        public string PADSIZEHxWxThid { get; set; }
        public string PADSIZEHxWxThid1 { get; set; }
        public Nullable<decimal> AirSpeedPossibleinShedFtMi { get; set; }
        public Nullable<decimal> FANSRequiredForHeatRemoval { get; set; }
        public Nullable<decimal> PadAreaSQFTReuiredFinal { get; set; }
        public Nullable<decimal> CoolingPadLengthSuggest { get; set; }
        public Nullable<decimal> CoolingPadLengthSuggest1 { get; set; }
        public Nullable<decimal> CoolPadDesigned { get; set; }
        public Nullable<decimal> BackWall { get; set; }
        public Nullable<decimal> BackWall1 { get; set; }
        public string LightTrap { get; set; }
        public Nullable<decimal> SingleStory { get; set; }
        public Nullable<decimal> OutMaxTempF { get; set; }
        public Nullable<decimal> MaxBirdWtKg { get; set; }
        public Nullable<decimal> InsulationR { get; set; }
        public Nullable<decimal> EffectiveHtBaffle { get; set; }
        public Nullable<decimal> RequiredAirSpeed { get; set; }
        public Nullable<decimal> FanRequired { get; set; }
        public Nullable<decimal> FanRequired1 { get; set; }
        public Nullable<decimal> FinalFanQt { get; set; }
        public Nullable<decimal> AirExchangemsec { get; set; }
        public Nullable<decimal> AirExchangemsec1 { get; set; }
        public Nullable<decimal> AirSpeedmsec { get; set; }
        public Nullable<decimal> AirInlets { get; set; }
        public string AirInlets1 { get; set; }
        public Nullable<decimal> MinVentFans { get; set; }
        public Nullable<int> CompId { get; set; }
        public string TransactionYear { get; set; }
        public Nullable<decimal> MaxAirFlow { get; set; }
        public Nullable<decimal> CostOfTotalSystem { get; set; }
        public Nullable<decimal> CostPerHouse { get; set; }
        public Nullable<decimal> CostPerBird { get; set; }
        public Nullable<decimal> Celcius { get; set; }
        public Nullable<decimal> MinVentFans1 { get; set; }
        public Nullable<decimal> CostOfTotalSystem1 { get; set; }
        public Nullable<decimal> VentPercent { get; set; }
    
        public virtual tblProjectAtGlanceMaster tblProjectAtGlanceMaster { get; set; }
        public virtual tblVentilationAndCoolingSystem tblVentilationAndCoolingSystem1 { get; set; }
        public virtual tblVentilationAndCoolingSystem tblVentilationAndCoolingSystem2 { get; set; }
        public virtual ICollection<tblVentilationAndCoolingSystemDetail> tblVentilationAndCoolingSystemDetails { get; set; }
    }
}
