//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThermalBillSetting
    {
        public int Id { get; set; }
        public string ShowMRP { get; set; }
        public string Settings { get; set; }
        public string Headings1 { get; set; }
        public string Headings2 { get; set; }
        public string Headings3 { get; set; }
        public string Headings4 { get; set; }
        public string Headings5 { get; set; }
        public string DispalySavings { get; set; }
        public Nullable<int> CompId { get; set; }
        public string Note { get; set; }
        public string DisplayDiscount { get; set; }
        public string CheckH1 { get; set; }
        public string CheckH2 { get; set; }
        public string CheckH3 { get; set; }
        public string CheckH4 { get; set; }
        public string CheckH5 { get; set; }
        public string PrintOnMarathiOrEnglish { get; set; }
        public string FontFamily { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<bool> GSTDetail { get; set; }
    }
}
