//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOInventorySystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tnlQuotationImge
    {
        public int Id { get; set; }
        public Nullable<int> ImageId { get; set; }
        public byte[] Image1 { get; set; }
        public byte[] Image2 { get; set; }
        public Nullable<int> CompId { get; set; }
        public byte[] MainImage { get; set; }
    }
}
